sudo: required
language: generic
services:
  - docker
deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "brainchild"
  env: "Brainchild-env"
  bucket_name: "elasticbeanstalk-eu-west-2-218844036683"
  bucket_path: "brainchild"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"